### ISSUE TITLE
bugs 🐛

### ISSUE THREAD

**Issue by hexahedron1** [dtplsongithub/ebgg#16]
- Back button in palette and name editor sends to main menu
- Save button in editor can crash
- Pattern resize button does nothing
- Can randomly crash
- ~~No backgrounds included~~

There are probably other things i forgot to mention

**Comment by Ponali** [comment]
i've made patches of some of the bugs you listed, but i can't find anything about bugs related to crashing. when you were running ebgg, were you low on memory? can you send us a log of the error from the console so i can see what's going on?

**Comment by hexahedron1** [comment]
[hs_err_pid7148.log](https://github.com/user-attachments/files/16267700/hs_err_pid7148.log)
[hs_err_pid15076.log](https://github.com/user-attachments/files/16267701/hs_err_pid15076.log)
[log.log](https://github.com/user-attachments/files/16267702/log.log)
eveything that has .log in the executable directory and i was nowhere remotely low on memory

**Comment by Ponali** [comment]
the two errors you got are "EXCEPTION_ACCESS_VIOLATION" errors, which is an issue with JRE and not the sketch code itself. i recommend you check for Java updates and search for other ways to fix this issue.

**Comment by dtplsongithub** [comment]
3rd and 5th problem mentioned were my fault, sorry ._.

dont aask why im saying this now

**Comment by dtplsongithub** [comment]
why wasnt this issue closed earlier?
